yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('group/<slug:slug>/', views.group_posts, name = 'group_list'),
    path('name/', views.name, name = 'name'),
    path('yandex/', views.yandex, name='yandex'),
]

yatube/yatube/urls.py
from django.contrib import admin

from django.urls import include, path


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),    
]

yatube/posts/models.py
from django.db import models

from django.contrib.auth import get_user_model


User = get_user_model() 


class Group (models.Model):
    title = models.CharField('Название группы', max_length=200)
    slug = models.SlugField('Краткое описание', unique=True)
    description = models.TextField('Описание')

    def __str__(self):
        return self.title
        

class Post(models.Model):
    text = models.TextField('Текст поста')
    pub_date = models.DateTimeField('Автор', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank = True,
        null = True,
        on_delete = models.SET_NULL,
        related_name='posts'
    )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post, Group

from django.http import HttpResponse


def index(request):    
    title = 'Последние обновления на сайте'
    text = 'Это главная страница проекта Yatube :))'
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'title': title,
        'text': text,
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    
    context = {
        'group': group,
        'posts': posts,        
    }
    return render(request, 'posts/group_list.html', context)


def name(request):
    return HttpResponse('<h1 style="color: red; font-size: 45px; margin: 20%;">Привет <i><b>путник!</b></i>')


def yandex(request):
    return HttpResponse("<a href='https://yandex.ru/'>Ссылка на <b>Яндекс</b></a>")

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block title %}
      Заголовок страницы
    {% endblock %}
  </head>
  
    {% include 'includes/header.html' %}    
    <main>
      {% block content %}
        Контент еще не подвезли
      {% endblock %}
    </main>
    {% include 'includes/footer.html' %}    

yatube/templates/includes/footer.html
<!-- Использованы классы бустрапа: -->
<!-- border-top: создаёт тонкую линию сверху блока -->
<!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
<!-- py-3: контент внутри размещается с отступом сверху и снизу -->
<footer class="border-top text-center py-3">
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
  <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
  <!-- В дальнейшем тут будет создано полноценное меню -->
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'img/icon.png' %}" width="30" height="30">
          <!-- <img src="img/logo.png" width="30" height="30" class="d-inline-block align-top" alt=""> -->
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Ya</span>tube
        </a>
      </div>
  </nav>
</header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} <title>Записи группы {{ group.title }}</title> {% endblock %}
{% include 'includes/header.html' %}    
{% block content %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    <h1 style = 'background:#0099CC; margin:0px'>*-- Группы --*</h1>
    <p><b>{{ group.title }}</b></p>
    {% for post in posts %}
      <article>
        <ul>
          <li style = 'background:#3399CC; margin:0px'>
            Автор: <b>{{ post.author.get_full_name }}</b>
          </li>
          <li style = 'background:#99CCFF; margin:0px'>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>          
      </article>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}    
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} <title>{{ title }}</title> {% endblock %}
      
    {% include 'includes/header.html' %}
    
      {% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        <h1>{{ text }}</h1>
        <article>
          {% for post in posts %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>      
          <p>{{ post.text }}</p>
          <!-- <a href=''>все записи группы</a> -->
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ group.title }}</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
        </article>
        <!-- под последним постом нет линии -->
      </div>
      {% endblock %}
    
    {% include 'includes/footer.html'%}